- name: Import common playbook
  import_playbook: common.yml

- hosts: localhost
  become: true

  roles:
    - { role: imwheel, tags: ['imwheel'] }
    - { role: mpd, tags: ['mpd'] }

  # tasks:
  #   # - include: tasks/packages.yml
  #   - include_tasks: tasks/packages.yml
