- name: Link asoundrc
  file:
    src: "/home/{{ user.name }}/{{ repo.dotfiles.dir_name }}/asoundrc"
    dest: "/home/{{ user.name }}/.asoundrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
