- name: Install mpd
  pacman: name=mpd state=present

- name: Create mpd config dir
  file:
    name: '/home/{{ user.name }}/.config/mpd'
    state: directory

- name: Link mpd.conf
  file:
    src: '/home/{{ user.name }}/{{ repo.dotfiles.dir_name }}/config/mpd/mpd.conf'
    dest: '/home/{{ user.name }}/.config/mpd/mpd.conf'
    owner: "{{ user.name }}"
    state: link

- name: Install cantata
  pacman: name=cantata state=present
