- name: Install imwheel
  pacman: name=imwheel state=present

- name: Link .imwheelrc
  become: yes
  become_user: "{{ user.name }}"
  file:
    src: "{{ repo.dotfiles.path }}/imwheelrc"
    dest: "/home/{{ user.name }}/.imwheelrc"
    state: link
