- name: Install imwheel
  pacman: name=imwheel state=present

- name: Link .imwheelrc
  file:
    src: '/home/{{ user.name }}/{{ repo.dotfiles.dir_name }}/imwheelrc'
    dest: '/home/{{ user.name }}/.imwheelrc'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
